### ISSUE TITLE
Activitynet 

### ISSUE THREAD

**Issue by PixelDoodle** [yuqi657/ts2_net#8]
Happy New Year. When I tested the accuracy on activitynet, I found that this line of code was very slow in extracting features.

`for bid, batch in enumerate(test_dataloader)`

 Is there any way to solve it?

**Comment by LiuRicky** [comment]
> Happy New Year. When I tested the accuracy on activitynet, I found that this line of code was very slow in extracting features.
> 
> `for bid, batch in enumerate(test_dataloader)`
> 
> Is there any way to solve it?

Sorry to reply late. Surely it is slow when training on long video (e.g. activitynet). It does take a long time and several things may affect it. It depends the cpu (for video uploading), the gpu (for computing). You could update your hardwares or just wait for it, since you may only test on activitynet for only one run.
